### ISSUE TITLE
Screenshot support

### ISSUE THREAD

**Issue by Holloweye** [ihptru/OpenRA-Content-Website#13]
Support for users to upload screenshots of a map or unit.

One map or unit should be able to have up to 5 screenshots.

Need 2 new tables probably:

Screenshot_group:
    - UID
    - image_id

Image:
    - UID
    - Image_path

probably a new attribute for both maps and units table:
     - screenshot_group_id

**Comment by ihptru** [comment]
displayItem() to have `upload screenshot` for an item's owner (above Delete item);
displayItem() >>> all screenshots (in preview mode: click for fullsize) are above comments block

Gallery >>> to show only screenshots
