### ISSUE TITLE
Contribute ImageMapGenerator to OpenRA

### ISSUE THREAD

**Issue by Mailaender** [ihptru/OpenRA-Content-Website#134]
Can you add https://github.com/Holloweye/OpenRA-Content-Website/tree/master/mono/ImageMapGenerator to OpenRA? @Iran asked for it at http://cnc-comm.com/community/index.php?topic=1619.msg12483#msg12483 and Harisson at http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=284404#284404.

**Comment by christerulfsparre** [comment]
No sources are left, would need to re-write it in that case.

**Comment by ihptru** [comment]
you have old sources still to start with in commits history

**Comment by mvdhout1992** [comment]
What about using a C#/.Net decompiler? The one JetBrains made is really good.

**Comment by ihptru** [comment]
https://github.com/OpenRA/OpenRA/issues/2762
