### ISSUE TITLE
wish: aud files on content

### ISSUE THREAD

**Issue by kyrreso** [ihptru/OpenRA-Content-Website#135]
Wish: host .aud files and have a player for audo files that work ingame... also fetch from current maps.....

**Comment by ihptru** [comment]
explain more about "have a player for audio files", and also about fetch from current maps, how do you want to see it?

**Comment by kyrreso** [comment]
Just a simple play |> play button, like: https://soundcloud.com/basement-jaxx/apdw-vs-basement-jaxx-red
And it should list all current aud files in .oramaps, like in this: http://content.open-ra.org/index.php?p=detail&table=maps&id=699
So, simple: a aud tab on the top, like units,maps
then, in map view: view yaml, play aud files, etc...

**Comment by christerulfsparre** [comment]
Not sure if this will be used a whole lot. Because it's difficult to find free sounds and not many people record their own sounds.

**Comment by kyrreso** [comment]
True. but at least it should be possible to post it somwhere on your site, just without the play, if you allow us to post .aud to shp, or zip with a lot of auds.... units-> type audio

**Comment by ihptru** [comment]
you always could post aud along with shp when you upload unit...

**Comment by kyrreso** [comment]
Please then allow .aud and make it a category of shp

**Comment by ihptru** [comment]
they were allowed, ex: http://content.open-ra.org/index.php?p=detail&table=units&id=132

what category you are talking about?
