### ISSUE TITLE
Replays link

### ISSUE THREAD

**Issue by xan2622** [ihptru/OpenRA-Content-Website#152]
Since replays are hosted here: 
http://www.gamereplays.org/openra/replays.php?game=92&tab=popular&show=index&tab_new=upcoming&display_mode=standard

I think we can now add this URL to the the http://resource.openra.net/Other/Replays link on the resource site.

![other_replays](https://cloud.githubusercontent.com/assets/1732773/8892952/1517b620-3379-11e5-97e7-4e586a7e59b4.png)

**Comment by Mailaender** [comment]
I don't think this whole "Other" sub menu is a good idea. It is very hard to discover and then also completely empty so why even keep it?

**Comment by xan2622** [comment]
About the empty links: they are just place-holders for upcoming pages.

btw, it seems I have created this issue in the wrong repository. Moved to https://github.com/OpenRA/OpenRA-Resources/issues/260
