### ISSUE TITLE
Edit Unit/Map/Guide

### ISSUE THREAD

**Issue by Holloweye** [ihptru/OpenRA-Content-Website#22]
Should be possible to edit a unit/map/guide.

**Comment by ihptru** [comment]
not editing map though

**Comment by Holloweye** [comment]
edit guide DONE (50% issue complete)

**Comment by ihptru** [comment]
editing guides has an issue with long text lines (where it comes out of range)

**Comment by ihptru** [comment]
Maps require editing `Additional info`

Edit: this is fixed in https://github.com/Holloweye/OpenRA-Content-Website/commit/ea8cf22d4d3fe20fa62d5845447e4432ba731e42
