### ISSUE TITLE
XHTML valid website

### ISSUE THREAD

**Issue by Holloweye** [ihptru/OpenRA-Content-Website#28]
website should be completely XHTML validated. "Valid web pages allow every browser to display web pages the way the author intended. Without valid code, your pages may look completely different, or not be readable in some browsers. To design an accessible website, the pages must be written in a valid markup language. As a bonus, search engines are beginning to rank valid websites higher. Your site will not become obsolete, if it remains valid. Quality websites are always valid. " quoted from http://www.seowebsitesdesigners.com/designing_websites/website_design_components.html

**Comment by ihptru** [comment]
rather difficult to reach this now and there is no one who would want to do it
