### ISSUE TITLE
SQL injection safe

### ISSUE THREAD

**Issue by Holloweye** [ihptru/OpenRA-Content-Website#30]
Should not be possible to sql inject the website.

**Comment by ihptru** [comment]
mostly done in https://github.com/Holloweye/OpenRA-Content-Website/commit/bcfb171f9cc6f3203de53e74c86d22ba709df71c
and in https://github.com/Holloweye/OpenRA-Content-Website/commit/8d57e26446a716ea209991c7bb5779a32c7ef624

**Comment by ihptru** [comment]
half done in https://github.com/Holloweye/OpenRA-Content-Website/commit/6a0b3dd34c32ab13f1d9378293da870e1718749d
still need to find a way how to do the same with SELECT and fix vulnerability in functions.php in delete_item()

**Comment by ihptru** [comment]
using PDO behind our db API might help, probably
