### ISSUE TITLE
Upload API for maps

### ISSUE THREAD

**Issue by Holloweye** [ihptru/OpenRA-Content-Website#35]

**Comment by ihptru** [comment]
uploading maps from android etc?

**Comment by Holloweye** [comment]
upload from example editor (built in upload function)

**Comment by ihptru** [comment]
fixed in https://github.com/Holloweye/OpenRA-Content-Website/commit/29b62e7e1d0eb3ed3bac97959ecfeba4f173ff68
usage example: https://github.com/ihptru/OpenRA-Content-MapUpload
