### ISSUE TITLE
Cross-platform/browser compatibility

### ISSUE THREAD

**Issue by Holloweye** [ihptru/OpenRA-Content-Website#43]
Should some what the same on following browsers:
- Firefox
- Chrome
- Safari
- Opera
- Internet explorer

Site should support following platforms (with specified UI to fit the platform):
- PC
- iPhone, Android, Windows Phone 7

**Comment by ihptru** [comment]
it mostly looks identical enough on all popular PC browsers

**Comment by ihptru** [comment]
unable to test on iPhone, Android, Windows Phone 7
