### ISSUE TITLE
upload picture

### ISSUE THREAD

**Issue by kyrreso** [ihptru/OpenRA-Content-Website#62]
Cannot upload picture for thumbnail.
Only says "not supported" thing....

**Comment by Holloweye** [comment]
Upload a thumbnail for a unit? Thumbnails are automatically created.

**Comment by kyrreso** [comment]
No, the profile picture

On Fri, Feb 17, 2012 at 7:12 AM, Christer U.L <
reply@reply.github.com

**Comment by ihptru** [comment]
Tried myself: can change profile image (avatar) without any problems

**Comment by kyrreso** [comment]
Sorry, guess this also was the problem with IE.. Please put up IE warnings...
firefox worked fine....

On Wed, Feb 22, 2012 at 9:21 PM, Igor Popov
reply@reply.github.com
wrote:

**Comment by ihptru** [comment]
thanks for informing, now IE requires investigation

**Comment by ihptru** [comment]
for someone did not work in Opera

**Comment by ihptru** [comment]
Looks like everyone can upload an avatar now, probably it was an issue with file size restriction which was fixed
