### ISSUE TITLE
Mouseover followed by

### ISSUE THREAD

**Issue by kyrreso** [ihptru/OpenRA-Content-Website#63]
When mouseover on followed by, the title only reads "thumbnail", not ihptru

**Comment by Holloweye** [comment]
Not reproducable

**Comment by kyrreso** [comment]
Sorry, only on I.E.

On Fri, Feb 17, 2012 at 9:10 AM, Christer U.L <
reply@reply.github.com

**Comment by ihptru** [comment]
seems fixed; did not test myself
