### ISSUE TITLE
server browser (and chat*)

### ISSUE THREAD

**Issue by ihptru** [ihptru/OpenRA-Content-Website#83]
once a new master server with a new bunch of stuff is ready, an improved server browser (with regex search etc) should be made and have to be available to be embedded into site (probably with a chat thing on the same page)

**Comment by ihptru** [comment]
if new master server is not going to be made any soon, use StreamServer https://github.com/ihptru/OpenRA-StreamServer

**Comment by ihptru** [comment]
server browser already exists at http://mailaender.name/openra/

**Comment by ihptru** [comment]
https://github.com/OpenRA/OpenRAWeb/pull/9

**Comment by Mailaender** [comment]
See https://kiwiirc.com or http://www.qwebirc.org/ if you want to host your own IRC webchat.
